demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

student/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'student'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    path('home', views.home, name='home'),
    path('add', views.add, name='add'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete,name='delete'),
    path('signup', views.signup, name='signup'),
    path('fees',views.fees, name='fees'),
    path('feededit/<int:pk>/',views.feededit, name='feededit'),
    path('showfees',views.showfees, name='showfees'),
    path('feesdelete/<int:pk>/',views.feesdelete, name='feesdelete')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.conf import settings


class Student(models.Model):
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=100)
    image = models.ImageField(upload_to='media/')
    user = models.ForeignKey(User,  on_delete=models.CASCADE)

    def __str__(self):
        return self.fname +" "+ self.lname


class StudentFees(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date = models.DateField(default=datetime.date.today)
    from_date = models.DateField(default=datetime.date.today)
    to_date = models.DateField(default=datetime.date.today)
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    comment = models.TextField(max_length=1000)

    def __str__(self):
        return self.student.fname + ' ' + self.student.lname

student/forms.py
from django import forms
from .models import Student,StudentFees
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['fname','lname','email','image','address']


class UserSignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2',]

class StudentFeesForm(forms.ModelForm):
    class Meta:
        model = StudentFees
        fields = ['date', 'from_date', 'to_date', 'amount', 'comment','student']

student/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from .forms import StudentForm,UserSignupForm,StudentFeesForm
from .models import Student ,StudentFees
from django.contrib.auth.decorators import login_required
from django.contrib import messages



@login_required(login_url='login')
def home(request):
    current_user = request.user.id

    show = Student.objects.filter(user = request.user.id)
    # show = Student.objects.all()
    return render(request, 'home.html', {'show': show})


def signup(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('student:login')
    else:
        form = UserSignupForm()

    return render(request, 'signup.html', {'form': form})


# def login(request):
#     if request.method == 'POST':
#         username = request.POST['email']
#         password1 = request.POST['password']
#         user = authenticate(request, username=username, password=password1)
#         if user is not None:
#             login(request, user)
#             return redirect('student:home')
#         else:
#             messages.warning(request, 'Please correct the error below.')
#     return render(request, 'login.html')

@login_required(login_url='login')

def add(request):

    if request.method == 'POST':
        form = StudentForm(request.POST,  request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.user = request.user
            f.save()
            return redirect('student:home')
    else:
        form = StudentForm()
    return render(request, 'add.html', {'form': form})


@login_required(login_url='login')
def update(request, pk):
    instance = get_object_or_404(Student, pk=pk)
    form = StudentForm(request.POST or None, request.FILES or None, instance=instance,)
    if form.is_valid():
        form.save()
        return redirect('student:home')
    return render(request, 'edit.html', {'form': form})


@login_required(login_url='login')
def delete(request, pk):

    show = Student.objects.get(pk=pk)
    show.delete()
    return redirect('student:home')


@login_required(login_url='login')
def fees(request):
    if request.method == "POST":

        form = StudentFeesForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'done')
            return redirect('student:showfees')
    else:

        form = StudentFeesForm()
    return render(request, 'manage_fees.html', {'form': form})


@login_required(login_url='login')
def showfees(request):
    show = StudentFees.objects.all()
    return render(request,'show_fees.html', {'show': show})


@login_required(login_url='login')
def feededit(request, pk):
    instance = get_object_or_404(StudentFees, pk=pk)
    form = StudentFeesForm(request.POST or None, instance=instance, )
    if form.is_valid():
        form.save()
        return redirect('student:showfees')
    return render(request, 'edite.html', {'form': form})


@login_required(login_url='login')
def feesdelete(request, pk):

    show = StudentFees.objects.get(pk=pk)
    show.delete()
    return redirect('student:showfees')

templates/add.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
           <div class="row">
              <form method="post"  enctype="multipart/form-data">
                     {% csrf_token %}
                    <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.fname|as_crispy_field }}
                      </div>
                      <div class="form-group col-md-6 mb-0">
                        {{ form.lname|as_crispy_field }}
                      </div>
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.email|as_crispy_field }}
                      </div>
                        <div class="form-group col-md-6 mb-0">
                        {{ form.image|as_crispy_field }}
                      </div>
                    </div>
                    {{ form.address|as_crispy_field }}
                    {% if not user.is_authenticated %}
                        {{ form.user }}
                    {% endif %}
                  {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <button type="submit" class="btn btn-primary">Add</button>
              </form>
            </div>

    </div>
{% endblock %}

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script>
function myFunction() {
  confirm("Press a button!");
}
</script>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow fixed-top">
          <div class="container">
            <a class="navbar-brand" href="#">Student</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">

                 {% if not user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'student:signup' %}">signup</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">login</a>
                </li>
                 {% else %}
                     <li class="nav-item active">
                  <a class="nav-link" href="{% url 'student:home' %}">Home
                        <span class="sr-only">(current)</span>
                      </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'student:add'%}" class="nav-link">Add</a>
                </li>
                 <li class="nav-item">
                   <div class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" id="about-us" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Fees
                        </button>
                        <div class="dropdown-menu" aria-labelledby="about-us">
                        <a class="dropdown-item" href="{% url 'student:fees' %}">Add Fees</a>
                        <a class="dropdown-item" href="{% url 'student:showfees' %}">Fees Details</a>
                        </div>
                        </div>
                  </li>
                     <li class="nav-item">
                    <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                </li>
                 {% endif %}
              </ul>
            </div>
          </div>
        </nav>





{#    <!-- Full Page Image Header with Vertically Centered Content -->#}
{#    <header class="masthead">#}
{#      <div class="container h-100">#}
{#        <div class="row h-100 align-items-center">#}
{#          <div class="col-12 text-center">#}
{#            <h1 class="font-weight-light">Vertically Centered Masthead Content</h1>#}
{#            <p class="lead">A great starter layout for a landing page</p>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </header>#}
    <!-- Page Content -->
    <section class="py-5" style="margin-top: 10px">
      <div class="container">
        {% block content %}
            content
        {% endblock %}
      </div>
    </section>
    </div>

</body>
</html>

templates/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% load crispy_forms_tags %}

    <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
        <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.fname|as_crispy_field }}
                      </div>
                      <div class="form-group col-md-6 mb-0">
                        {{ form.lname|as_crispy_field }}
                      </div>
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.email|as_crispy_field }}
                      </div>
                        <div class="form-group col-md-6 mb-0">
                        {{ form.image|as_crispy_field }}
                      </div>
                    </div>
                    {{ form.address|as_crispy_field }}
            <button type="submit" >Edit</button>
        </div>
    </form>

{% block javascript %}
    <script>
    function ConfirmEdit()
    {
      var x = confirm("Are you sure you want to delete?");
      if (x)
          return true;
      else
          return false;
    }
</script>
{% endblock %}

{% endblock %}

templates/edite.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
      <div class="container">
           <div class="row">
              <form method="post"  enctype="multipart/form-data">
                     {% csrf_token %}
                    <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.student|as_crispy_field }}
                      </div>
                      <div class="form-group col-md-6 mb-0">
                        {{ form.date|as_crispy_field }}
                      </div>
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.from_date|as_crispy_field }}
                      </div>
                        <div class="form-group col-md-6 mb-0">
                        {{ form.to_date|as_crispy_field }}
                      </div>
                    </div>
                <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.amount|as_crispy_field }}
                      </div>
                    </div>
                    {{ form.comment|as_crispy_field }}
                  {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <button type="submit" class="btn btn-primary">Add</button>
              </form>
            </div>

    </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col"> image</th>
          <th scope="col">first name</th>
          <th scope="col">Lastname</th>
          <th scope="col">Email</th>
          <th scope="col">Address</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>


        </tr>
                {% for item in show %}
      <tbody>
        <tr>
          <td><img src="{{ item.image.url }}"  style="width:50px;height:40px;"></td>
          <td>{{ item.fname }}</td>
          <td>{{ item.lname }}</td>
          <td>{{ item.email }}</td>
          <td>{{ item.address }}</td>
            <td><a href="{% url 'student:update' item.pk %}" >Edit</a></td>
          <td><a href="{% url 'student:delete' item.pk %}" onclick="myFunction()">Delete</a></td>
        </tr>
      </tbody>
            {% endfor %}
</table>
{% endblock %}

templates/manage_fees.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
      <div class="container">
           <div class="row">
              <form method="post"  enctype="multipart/form-data">
                     {% csrf_token %}
                    <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.student|as_crispy_field }}
                      </div>
                      <div class="form-group col-md-6 mb-0">
                        {{ form.date|as_crispy_field }}
                      </div>
                    </div>
                    <div class="form-row">
                      <div class="form-group col-md-6 mb-0">
                        {{ form.from_date|as_crispy_field }}
                      </div>
                        <div class="form-group col-md-6 mb-0">
                        {{ form.to_date|as_crispy_field }}
                      </div>
                    </div>
                    {{ form.comment|as_crispy_field }}
                  {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <button type="submit" class="btn btn-primary">Add</button>
              </form>
            </div>

    </div>
{% endblock %}

templates/show_fees.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <table class="table table-hover">
      <thead>
        <tr>
{#          <th scope="col">No</th>#}
          <th scope="col">Date</th>
          <th scope="col">name</th>
          <th scope="col">amount</th>
          <th scope="col">time</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>


        </tr>
                {% for item in show %}
      <tbody>
        <tr>
          <td>{{ item.date }}</td>
          <td>{{ item.student.fname }}</td>
          <td>{{ item.amount }}</td>
          <td>{{ item.from_date }} to {{ item.to_date }}</td>
            <td><a href="{% url 'student:feededit' item.pk %}" >Edit</a></td>
          <td><a href="{% url 'student:feesdelete' item.pk %}" onclick="myFunction()">Delete</a></td>
        </tr>
      </tbody>
            {% endfor %}
</table>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
     <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">Register</div>
                        <div class="card-body">
                            <form name="my-form" action="" method="post">
                                {% csrf_token %}
                                <div class="form-group row">
{#                                 <label for="full_name" class="col-md-4 col-form- text-md-right">{{ form.first_name.label_tag }}</label>#}
                                    <div class="col-md-6">
                                        {{ form.username|as_crispy_field }}
                                    </div>
                                </div>


                                <div class="form-group row">
{#                                    <label for="user_name" class="col-md-4 col-form-label text-md-right">User Name</label>#}
                                    <div class="col-md-6">
                                       {{ form.email|as_crispy_field }}
                                    </div>
                                </div>

                                <div class="form-group row">
{#                                    <label for="phone_number" class="col-md-4 col-form-label text-md-right">Phone Number</label>#}
                                    <div class="col-md-6">
                                        {{ form.password1|as_crispy_field }}
                                    </div>
                                </div>

                                <div class="form-group row">
{#                                    <label for="present_address" class="col-md-4 col-form-label text-md-right">Present Address</label>#}
                                    <div class="col-md-6">
                                        {{ form.password2|as_crispy_field }}
                                    </div>
                                </div>
                                    <div class="col-md-6 offset-md-4">
                                        <button type="submit" class="btn btn-primary">
                                        Register
                                        </button>
                                        <a href="{% url 'student:login' %}" class="btn btn-primary">
                                        Login
                                        </a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}